### ISSUE TITLE
Use surface forms in examples

### ISSUE THREAD

**Issue by fcbond** [fcbond/ltdb#38]
LTDB currently displays lemmas in examples; does that depend on LTDB code or on something else (ACE output)?..

Would be much more convenient to see the examples with surface forms... Especially when they get longer, having just lemmas in Spanish can be confusing :).

**Comment by olzama** [comment]
Perhaps I could tackle this; where should I start looking in the source code?..

**Comment by arademaker** [comment]
Hi @fcbond do you have LTDB running in a public endpoint? So we can see what your comment means?

**Comment by olzama** [comment]
@arademaker Francis's comment is actually my email to him :).

LTDB currently displays lemmas instead of surface forms in corpus examples; that's rather inconvenient for non-English languages...

**Comment by olzama** [comment]
I got as far as setting up Pycharm as the debugger:

![Screenshot from 2023-11-10 17-15-53](https://github.com/fcbond/ltdb/assets/10963114/f4c3ab5d-8a61-4dda-b60b-b98c56a97f68)

But I can't figure out where the relevant code is, for the examples that get displayed. Any help? Where should I try to set the breakpoint?

**Comment by fcbond** [comment]
The lex-rule is shown by the route

https://github.com/fcbond/ltdb/blob/dbbc9f9406b6e8a864e212d695d97fcacd6a16d8/web/routes.py#L102-L104

Which somewhat confusingly is rendered by the lextype template, which displays the sentences as such:
https://github.com/fcbond/ltdb/blob/dbbc9f9406b6e8a864e212d695d97fcacd6a16d8/web/templates/lextype.html#L80-L89

**Comment by fcbond** [comment]
The problem is that the words in the `sents` dictionary are the terminals of the trees:
https://github.com/fcbond/ltdb/blob/dbbc9f9406b6e8a864e212d695d97fcacd6a16d8/scripts/gold2db.py#L111C13-L120C67

In grammars using an external morphological analyzer like the SRG, these are probably the lemmas.   I don't know where the surface form is stored .

Ideally we should be able to link back to cfrom-cto, and then use the original sentence, ...

**Comment by olzama** [comment]
See if it can be fixed like this maybe? https://github.com/fcbond/ltdb/pull/39
